### ISSUE TITLE
How do I run this code on my dataset?

### ISSUE THREAD

**Issue by Monikshah** [jindongwang/Pytorch-CapsuleNet#11]

**Comment by jindongwang** [comment]
You can change the dataloader section to load your data. Then, you need to modify the model structure to better fit your data dimensions.

**Comment by Monikshah** [comment]
I was able to run the code on my dataset. I was able to train the model.  Thank you very much.

I still have an issue. I want to use capsnet for classification. so I eliminated the decoder part, I assume just the encoder should do this part. Now I want to save the encoded features for further work. Can you please help me with what part I will need to save, I mean what variable in your code?

**Comment by Monikshah** [comment]
This is the first time I am using capsnet, I don't understand the details much. So I am confused if the features are represented in the PrimaryCaps or the DigitCaps.
