### ISSUE TITLE
How does this compares to the other projects

### ISSUE THREAD

**Issue by elgalu** [jindongwang/Pytorch-CapsuleNet#2]
Hi, How does this compares to the other projects?

- https://github.com/gram-ai/capsule-networks
- https://github.com/higgsfield/Capsule-Network-Tutorial
- https://github.com/danielhavir/capsule-network
- https://github.com/jindongwang/Pytorch-CapsuleNet (this one)

Should you include your project also in this list?
https://github.com/sekwiatkowski/awesome-capsule-networks#pytorch

**Comment by CielAl** [comment]
I did not perform a thorough inspection nor benchmarks but it appears that the logic beneath the implementations is quite the same. Depending on how the author designed the interface/arrange the structures, there might be tiny differences regarding usability.
