### ISSUE TITLE
Low test accuracy of 0.1

### ISSUE THREAD

**Issue by buttercutter** [jindongwang/Pytorch-CapsuleNet#3]
Why does your CapsuleNet coding resulted in [test accuracy of only 0.1](https://colab.research.google.com/drive/1UAjdZXQY4cm2RtL9JyfPnmA_APNHT4hX) ?

> Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar/cifar-10-python.tar.gz
> 170500096it [00:02, 74718714.99it/s]                   
> Files already downloaded and verified
> Epoch: [1/30], Batch: [1/500], train accuracy: 0.080000, loss: 0.009003
> Epoch: [1/30], Batch: [101/500], train accuracy: 0.400000, loss: 0.008004
> Epoch: [1/30], Batch: [201/500], train accuracy: 0.390000, loss: 0.008002
> Epoch: [1/30], Batch: [301/500], train accuracy: 0.340000, loss: 0.008003
> Epoch: [1/30], Batch: [401/500], train accuracy: 0.400000, loss: 0.007995
> 100% 500/500 [02:44<00:00,  2.95it/s]
> Epoch: [1/30], train loss: 0.008047
> Epoch: [1/30], test accuracy: 0.431800, loss: 0.797698
> Epoch: [2/30], Batch: [1/500], train accuracy: 0.480000, loss: 0.007946
> Epoch: [2/30], Batch: [101/500], train accuracy: 0.360000, loss: 0.007998
> Epoch: [2/30], Batch: [201/500], train accuracy: 0.470000, loss: 0.007937
> Epoch: [2/30], Batch: [301/500], train accuracy: 0.510000, loss: 0.007817
> Epoch: [2/30], Batch: [401/500], train accuracy: 0.400000, loss: 0.007882
> 100% 500/500 [02:45<00:00,  3.04it/s]
> Epoch: [2/30], train loss: 0.007874
> Epoch: [2/30], test accuracy: 0.468100, loss: 0.769648
> Epoch: [3/30], Batch: [1/500], train accuracy: 0.480000, loss: 0.007770
> Epoch: [3/30], Batch: [101/500], train accuracy: 0.500000, loss: 0.007449
> Epoch: [3/30], Batch: [201/500], train accuracy: 0.490000, loss: 0.007445
> Epoch: [3/30], Batch: [301/500], train accuracy: 0.410000, loss: 0.007163
> Epoch: [3/30], Batch: [401/500], train accuracy: 0.450000, loss: 0.007121
> 100% 500/500 [02:44<00:00,  3.04it/s]
> Epoch: [3/30], train loss: 0.007182
> Epoch: [3/30], test accuracy: 0.521300, loss: 0.662147
> Epoch: [4/30], Batch: [1/500], train accuracy: 0.470000, loss: 0.007082
> Epoch: [4/30], Batch: [101/500], train accuracy: 0.560000, loss: 0.006161
> Epoch: [4/30], Batch: [201/500], train accuracy: 0.560000, loss: 0.006386
> Epoch: [4/30], Batch: [301/500], train accuracy: 0.590000, loss: 0.006173
> Epoch: [4/30], Batch: [401/500], train accuracy: 0.560000, loss: 0.006173
> 100% 500/500 [02:44<00:00,  3.04it/s]
> Epoch: [4/30], train loss: 0.006349
> Epoch: [4/30], test accuracy: 0.555800, loss: 0.612919
> Epoch: [5/30], Batch: [1/500], train accuracy: 0.590000, loss: 0.005984
> Epoch: [5/30], Batch: [101/500], train accuracy: 0.540000, loss: 0.005862
> Epoch: [5/30], Batch: [201/500], train accuracy: 0.560000, loss: 0.006026
> Epoch: [5/30], Batch: [301/500], train accuracy: 0.580000, loss: 0.005553
> Epoch: [5/30], Batch: [401/500], train accuracy: 0.680000, loss: 0.005457
> 100% 500/500 [02:44<00:00,  3.05it/s]
> Epoch: [5/30], train loss: 0.005918
> Epoch: [5/30], test accuracy: 0.590500, loss: 0.580702
> Epoch: [6/30], Batch: [1/500], train accuracy: 0.660000, loss: 0.005525
> Epoch: [6/30], Batch: [101/500], train accuracy: 0.580000, loss: 0.005722
> Epoch: [6/30], Batch: [201/500], train accuracy: 0.610000, loss: 0.005729
> Epoch: [6/30], Batch: [301/500], train accuracy: 0.580000, loss: 0.005752
> Epoch: [6/30], Batch: [401/500], train accuracy: 0.570000, loss: 0.005795
> 100% 500/500 [02:44<00:00,  3.05it/s]
> Epoch: [6/30], train loss: 0.005638
> Epoch: [6/30], test accuracy: 0.602900, loss: 0.562709
> Epoch: [7/30], Batch: [1/500], train accuracy: 0.640000, loss: 0.005054
> Epoch: [7/30], Batch: [101/500], train accuracy: 0.630000, loss: 0.005274
> Epoch: [7/30], Batch: [201/500], train accuracy: 0.640000, loss: 0.005245
> Epoch: [7/30], Batch: [301/500], train accuracy: 0.600000, loss: 0.005418
> Epoch: [7/30], Batch: [401/500], train accuracy: 0.630000, loss: 0.004710
> 100% 500/500 [02:44<00:00,  3.06it/s]
> Epoch: [7/30], train loss: 0.005448
> Epoch: [7/30], test accuracy: 0.616700, loss: 0.547133
> Epoch: [8/30], Batch: [1/500], train accuracy: 0.650000, loss: 0.005194
> Epoch: [8/30], Batch: [101/500], train accuracy: 0.690000, loss: 0.004807
> Epoch: [8/30], Batch: [201/500], train accuracy: 0.690000, loss: 0.005423
> Epoch: [8/30], Batch: [301/500], train accuracy: 0.640000, loss: 0.005231
> Epoch: [8/30], Batch: [401/500], train accuracy: 0.670000, loss: 0.004982
> 100% 500/500 [02:44<00:00,  3.04it/s]
> Epoch: [8/30], train loss: 0.005282
> Epoch: [8/30], test accuracy: 0.632800, loss: 0.534200
> Epoch: [9/30], Batch: [1/500], train accuracy: 0.640000, loss: 0.005729
> Epoch: [9/30], Batch: [101/500], train accuracy: 0.700000, loss: 0.004558
> Epoch: [9/30], Batch: [201/500], train accuracy: 0.640000, loss: 0.005404
> Epoch: [9/30], Batch: [301/500], train accuracy: 0.670000, loss: 0.005204
> Epoch: [9/30], Batch: [401/500], train accuracy: 0.600000, loss: 0.005491
> 100% 500/500 [02:44<00:00,  3.05it/s]
> Epoch: [9/30], train loss: 0.005110
> Epoch: [9/30], test accuracy: 0.640100, loss: 0.525246
> Epoch: [10/30], Batch: [1/500], train accuracy: 0.700000, loss: 0.004635
> Epoch: [10/30], Batch: [101/500], train accuracy: 0.670000, loss: 0.005026
> Epoch: [10/30], Batch: [201/500], train accuracy: 0.710000, loss: 0.004482
> Epoch: [10/30], Batch: [301/500], train accuracy: 0.730000, loss: 0.004045
> Epoch: [10/30], Batch: [401/500], train accuracy: 0.640000, loss: 0.005618
> 100% 500/500 [02:44<00:00,  3.04it/s]
> Epoch: [10/30], train loss: 0.005005
> Epoch: [10/30], test accuracy: 0.656500, loss: 0.507344
> Epoch: [11/30], Batch: [1/500], train accuracy: 0.640000, loss: 0.005273
> Epoch: [11/30], Batch: [101/500], train accuracy: 0.640000, loss: 0.005570
> Epoch: [11/30], Batch: [201/500], train accuracy: 0.750000, loss: 0.004569
> Epoch: [11/30], Batch: [301/500], train accuracy: 0.640000, loss: 0.005356
> Epoch: [11/30], Batch: [401/500], train accuracy: 0.670000, loss: 0.004885
> 100% 500/500 [02:44<00:00,  3.02it/s]
> Epoch: [11/30], train loss: 0.004867
> Epoch: [11/30], test accuracy: 0.659600, loss: 0.506003
> Epoch: [12/30], Batch: [1/500], train accuracy: 0.680000, loss: 0.004995
> Epoch: [12/30], Batch: [101/500], train accuracy: 0.650000, loss: 0.004921
> Epoch: [12/30], Batch: [201/500], train accuracy: 0.650000, loss: 0.005072
> Epoch: [12/30], Batch: [301/500], train accuracy: 0.680000, loss: 0.004890
> Epoch: [12/30], Batch: [401/500], train accuracy: 0.600000, loss: 0.005777
> 100% 500/500 [02:44<00:00,  3.04it/s]
> Epoch: [12/30], train loss: 0.004758
> Epoch: [12/30], test accuracy: 0.669700, loss: 0.492968
> Epoch: [13/30], Batch: [1/500], train accuracy: 0.650000, loss: 0.004795
> Epoch: [13/30], Batch: [101/500], train accuracy: 0.730000, loss: 0.004316
> Epoch: [13/30], Batch: [201/500], train accuracy: 0.720000, loss: 0.003964
> Epoch: [13/30], Batch: [301/500], train accuracy: 0.760000, loss: 0.004180
> Epoch: [13/30], Batch: [401/500], train accuracy: 0.710000, loss: 0.004485
> 100% 500/500 [02:44<00:00,  3.06it/s]
> Epoch: [13/30], train loss: 0.004673
> Epoch: [13/30], test accuracy: 0.672600, loss: 0.498016
> Epoch: [14/30], Batch: [1/500], train accuracy: 0.700000, loss: 0.004716
> Epoch: [14/30], Batch: [101/500], train accuracy: 0.720000, loss: 0.004677
> Epoch: [14/30], Batch: [201/500], train accuracy: 0.720000, loss: 0.004923
> Epoch: [14/30], Batch: [301/500], train accuracy: 0.720000, loss: 0.003978
> Epoch: [14/30], Batch: [401/500], train accuracy: 0.760000, loss: 0.004141
> 100% 500/500 [02:44<00:00,  3.03it/s]
> Epoch: [14/30], train loss: 0.004577
> Epoch: [14/30], test accuracy: 0.675800, loss: 0.487264
> Epoch: [15/30], Batch: [1/500], train accuracy: 0.700000, loss: 0.004650
> Epoch: [15/30], Batch: [101/500], train accuracy: 0.790000, loss: 0.003771
> Epoch: [15/30], Batch: [201/500], train accuracy: 0.690000, loss: 0.004529
> Epoch: [15/30], Batch: [301/500], train accuracy: 0.660000, loss: 0.005128
> Epoch: [15/30], Batch: [401/500], train accuracy: 0.730000, loss: 0.004389
> 100% 500/500 [02:44<00:00,  3.06it/s]
> Epoch: [15/30], train loss: 0.004505
> Epoch: [15/30], test accuracy: 0.684100, loss: 0.483410
> Epoch: [16/30], Batch: [1/500], train accuracy: 0.630000, loss: 0.005254
> Epoch: [16/30], Batch: [101/500], train accuracy: 0.770000, loss: 0.004265
> Epoch: [16/30], Batch: [201/500], train accuracy: 0.710000, loss: 0.004419
> Epoch: [16/30], Batch: [301/500], train accuracy: 0.690000, loss: 0.004336
> Epoch: [16/30], Batch: [401/500], train accuracy: 0.740000, loss: 0.004540
> 100% 500/500 [02:44<00:00,  3.04it/s]
> Epoch: [16/30], train loss: 0.004415
> Epoch: [16/30], test accuracy: 0.683000, loss: 0.482916
> Epoch: [17/30], Batch: [1/500], train accuracy: 0.740000, loss: 0.004360
> Epoch: [17/30], Batch: [101/500], train accuracy: 0.630000, loss: 0.005027
> Epoch: [17/30], Batch: [201/500], train accuracy: 0.720000, loss: 0.004651
> Epoch: [17/30], Batch: [301/500], train accuracy: 0.690000, loss: 0.004591
> Epoch: [17/30], Batch: [401/500], train accuracy: 0.800000, loss: 0.003930
> 100% 500/500 [02:44<00:00,  3.09it/s]
> Epoch: [17/30], train loss: nan
> Epoch: [17/30], test accuracy: 0.100000, loss: nan
> Epoch: [18/30], Batch: [1/500], train accuracy: 0.050000, loss: nan
> Epoch: [18/30], Batch: [101/500], train accuracy: 0.100000, loss: nan
> Epoch: [18/30], Batch: [201/500], train accuracy: 0.080000, loss: nan
> Epoch: [18/30], Batch: [301/500], train accuracy: 0.060000, loss: nan
> Epoch: [18/30], Batch: [401/500], train accuracy: 0.040000, loss: nan
> 100% 500/500 [02:39<00:00,  3.15it/s]
> Epoch: [18/30], train loss: nan
> Epoch: [18/30], test accuracy: 0.100000, loss: nan
> Epoch: [19/30], Batch: [1/500], train accuracy: 0.070000, loss: nan
> Epoch: [19/30], Batch: [101/500], train accuracy: 0.130000, loss: nan
> Epoch: [19/30], Batch: [201/500], train accuracy: 0.110000, loss: nan
> Epoch: [19/30], Batch: [301/500], train accuracy: 0.110000, loss: nan
> Epoch: [19/30], Batch: [401/500], train accuracy: 0.170000, loss: nan
> 100% 500/500 [02:39<00:00,  3.15it/s]
> Epoch: [19/30], train loss: nan
> Epoch: [19/30], test accuracy: 0.100000, loss: nan
> Epoch: [20/30], Batch: [1/500], train accuracy: 0.080000, loss: nan
> Epoch: [20/30], Batch: [101/500], train accuracy: 0.110000, loss: nan
> Epoch: [20/30], Batch: [201/500], train accuracy: 0.160000, loss: nan
> Epoch: [20/30], Batch: [301/500], train accuracy: 0.090000, loss: nan
> Epoch: [20/30], Batch: [401/500], train accuracy: 0.080000, loss: nan
> 100% 500/500 [02:39<00:00,  3.15it/s]
> Epoch: [20/30], train loss: nan
> Epoch: [20/30], test accuracy: 0.100000, loss: nan
> Epoch: [21/30], Batch: [1/500], train accuracy: 0.090000, loss: nan
> Epoch: [21/30], Batch: [101/500], train accuracy: 0.110000, loss: nan
> Epoch: [21/30], Batch: [201/500], train accuracy: 0.100000, loss: nan
> Epoch: [21/30], Batch: [301/500], train accuracy: 0.100000, loss: nan
> Epoch: [21/30], Batch: [401/500], train accuracy: 0.110000, loss: nan
> 100% 500/500 [02:39<00:00,  3.15it/s]
> Epoch: [21/30], train loss: nan
> Epoch: [21/30], test accuracy: 0.100000, loss: nan
> Epoch: [22/30], Batch: [1/500], train accuracy: 0.080000, loss: nan
> Epoch: [22/30], Batch: [101/500], train accuracy: 0.160000, loss: nan
> Epoch: [22/30], Batch: [201/500], train accuracy: 0.110000, loss: nan
> Epoch: [22/30], Batch: [301/500], train accuracy: 0.140000, loss: nan
> Epoch: [22/30], Batch: [401/500], train accuracy: 0.100000, loss: nan
> 100% 500/500 [02:38<00:00,  3.16it/s]
> Epoch: [22/30], train loss: nan
> Epoch: [22/30], test accuracy: 0.100000, loss: nan
> Epoch: [23/30], Batch: [1/500], train accuracy: 0.100000, loss: nan
> Epoch: [23/30], Batch: [101/500], train accuracy: 0.080000, loss: nan
> Epoch: [23/30], Batch: [201/500], train accuracy: 0.100000, loss: nan
> Epoch: [23/30], Batch: [301/500], train accuracy: 0.090000, loss: nan
> Epoch: [23/30], Batch: [401/500], train accuracy: 0.100000, loss: nan
> 100% 500/500 [02:38<00:00,  3.16it/s]
> Epoch: [23/30], train loss: nan
> Epoch: [23/30], test accuracy: 0.100000, loss: nan
> Epoch: [24/30], Batch: [1/500], train accuracy: 0.070000, loss: nan
> Epoch: [24/30], Batch: [101/500], train accuracy: 0.110000, loss: nan
> Epoch: [24/30], Batch: [201/500], train accuracy: 0.080000, loss: nan
> Epoch: [24/30], Batch: [301/500], train accuracy: 0.080000, loss: nan
> Epoch: [24/30], Batch: [401/500], train accuracy: 0.110000, loss: nan
> 100% 500/500 [02:39<00:00,  3.14it/s]
> Epoch: [24/30], train loss: nan
> Epoch: [24/30], test accuracy: 0.100000, loss: nan
> Epoch: [25/30], Batch: [1/500], train accuracy: 0.090000, loss: nan
> Epoch: [25/30], Batch: [101/500], train accuracy: 0.070000, loss: nan
> Epoch: [25/30], Batch: [201/500], train accuracy: 0.100000, loss: nan
> Epoch: [25/30], Batch: [301/500], train accuracy: 0.110000, loss: nan
> Epoch: [25/30], Batch: [401/500], train accuracy: 0.110000, loss: nan
> 100% 500/500 [02:39<00:00,  3.14it/s]
> Epoch: [25/30], train loss: nan
> Epoch: [25/30], test accuracy: 0.100000, loss: nan
> Epoch: [26/30], Batch: [1/500], train accuracy: 0.130000, loss: nan
> Epoch: [26/30], Batch: [101/500], train accuracy: 0.050000, loss: nan
> Epoch: [26/30], Batch: [201/500], train accuracy: 0.070000, loss: nan
> Epoch: [26/30], Batch: [301/500], train accuracy: 0.100000, loss: nan
> Epoch: [26/30], Batch: [401/500], train accuracy: 0.120000, loss: nan
> 100% 500/500 [02:38<00:00,  3.16it/s]
> Epoch: [26/30], train loss: nan
> Epoch: [26/30], test accuracy: 0.100000, loss: nan
> Epoch: [27/30], Batch: [1/500], train accuracy: 0.100000, loss: nan
> Epoch: [27/30], Batch: [101/500], train accuracy: 0.090000, loss: nan
> Epoch: [27/30], Batch: [201/500], train accuracy: 0.090000, loss: nan
> Epoch: [27/30], Batch: [301/500], train accuracy: 0.050000, loss: nan
> Epoch: [27/30], Batch: [401/500], train accuracy: 0.090000, loss: nan
> 100% 500/500 [02:39<00:00,  3.15it/s]
> Epoch: [27/30], train loss: nan
> Epoch: [27/30], test accuracy: 0.100000, loss: nan
> Epoch: [28/30], Batch: [1/500], train accuracy: 0.100000, loss: nan
> Epoch: [28/30], Batch: [101/500], train accuracy: 0.080000, loss: nan
> Epoch: [28/30], Batch: [201/500], train accuracy: 0.080000, loss: nan
> Epoch: [28/30], Batch: [301/500], train accuracy: 0.070000, loss: nan
> Epoch: [28/30], Batch: [401/500], train accuracy: 0.100000, loss: nan
> 100% 500/500 [02:39<00:00,  3.15it/s]
> Epoch: [28/30], train loss: nan
> Epoch: [28/30], test accuracy: 0.100000, loss: nan
> Epoch: [29/30], Batch: [1/500], train accuracy: 0.060000, loss: nan
> Epoch: [29/30], Batch: [101/500], train accuracy: 0.090000, loss: nan
> Epoch: [29/30], Batch: [201/500], train accuracy: 0.100000, loss: nan
> Epoch: [29/30], Batch: [301/500], train accuracy: 0.100000, loss: nan
> Epoch: [29/30], Batch: [401/500], train accuracy: 0.100000, loss: nan
> 100% 500/500 [02:39<00:00,  3.16it/s]
> Epoch: [29/30], train loss: nan
> Epoch: [29/30], test accuracy: 0.100000, loss: nan
> Epoch: [30/30], Batch: [1/500], train accuracy: 0.130000, loss: nan
> Epoch: [30/30], Batch: [101/500], train accuracy: 0.080000, loss: nan
> Epoch: [30/30], Batch: [201/500], train accuracy: 0.080000, loss: nan
> Epoch: [30/30], Batch: [301/500], train accuracy: 0.100000, loss: nan
> Epoch: [30/30], Batch: [401/500], train accuracy: 0.110000, loss: nan
> 100% 500/500 [02:39<00:00,  3.11it/s]
> Epoch: [30/30], train loss: nan
> Epoch: [30/30], test accuracy: 0.100000, loss: nan

**Comment by amobiny** [comment]
Similar to others, I found many issues with this implementation. So I decided to create my own one. It is bug-free and works very good. You can find it here:

https://github.com/hula-ai/capsule_network_dynamic_routing

**Comment by saswatpp** [comment]
its because the loss is nan. The cause of this is that the squash function is not numerically stable.
